[credentials] 
    [credentials.admin]
    username = "admin"
    password = "admin_pw"

    [credentials.111]
    username = "111"
    password = "111_pw"

[database]
DATABASE_URL="postgresql://postgres.[streamlit_key]:[password]@aws-1-ap-northeast-1.pooler.supabase.com:6543/postgres"